// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_grid: dynamic(() => import("./BlogGrid")),
  blog_post: dynamic(() => import("./BlogPost")),
  rich_text: dynamic(() => import("./RichText")),
};
