// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_grid: dynamic(() => import("./BlogGrid")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  news_letter: dynamic(() => import("./NewsLetter")),
  rich_text: dynamic(() => import("./RichText")),
};
